### ISSUE TITLE
Product Category Grid does not match Design

### ISSUE THREAD

**Issue by rcass** [NguyenKhoa2014/project02-aloha#4]
The product category needs some more CSS love to get it to reflect the designs and demo site more closely.

![screen shot 2017-02-07 at 4 46 35 pm](https://cloud.githubusercontent.com/assets/5028555/22718421/2a4a651e-ed55-11e6-9fb6-798365b52e3e.png)

**Comment by NguyenKhoa2014** [comment]
issue is fixed
